In [ ]:
import numpy as np
# np.polyval()
# Description: Evaluates a polynomial at specific values.
# Example:
p = np.poly1d([1, 2, 3])
val = np.polyval(p, np.array([0, 1, 2]))
print(val)


[ 3  6 11]


In [ ]:
# np.polyder()
# Description: Computes the derivative of a polynomial.
# Example:
p = np.poly1d([1, 2, 3])
derivative = np.polyder(p)
print(derivative)


 
2 x + 2


In [ ]:
# np.roots()
# Description: Finds the roots of a polynomial.
# Example:
p = np.poly1d([1, 0, -1])
roots = np.roots(p)
print(roots)


[-1.  1.]


In [ ]:
# np.poly()
# Description: Finds the coefficients of a polynomial with given roots.
# Example:
roots = [1, 2, 3]
coefficients = np.poly(roots)
print(coefficients)


[ 1. -6. 11. -6.]


In [ ]:
# np.vander()
# Description: Generates a Vandermonde matrix.
# Example:
x = np.array([1, 2, 3, 5])
V = np.vander(x)
print(V)


[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [ ]:
# np.trapz()
# Description: Performs trapezoidal integration.
# Example:
y = np.array([1, 2, 3])
x = np.array([4, 6, 8])
area = np.trapz(y, x)
print(area)


8.0


In [ ]:
# np.linspace()
# Description: Returns evenly spaced numbers over a specified interval.
# Example:
arr = np.linspace(0, 10, 5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# np.logspace()
# Description: Returns numbers spaced evenly on a log scale.
# Example:
arr = np.logspace(0, 2, 4)
print(arr)


[  1.           4.64158883  21.5443469  100.        ]


In [ ]:
# np.geomspace()
# Description: Returns numbers spaced evenly on a geometric progression.
# Example:
arr = np.geomspace(1, 1000, 4)
print(arr)


[   1.   10.  100. 1000.]


In [ ]:
# np.fft.fft()
# Description: Computes the one-dimensional discrete Fourier Transform.
# Example:
arr = np.fft.fft(np.array([1, 2, 3, 4]))
print(arr)


[10.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [ ]:
# np.fft.ifft()
# Description: Computes the one-dimensional inverse discrete Fourier Transform.
# Example:
arr = np.fft.ifft(np.array([1, 2, 3, 4]))
print(arr)


[ 2.5+0.j  -0.5-0.5j -0.5+0.j  -0.5+0.5j]


In [ ]:
# np.fft.fftshift()
# Description: Shifts the zero-frequency component to the center of the spectrum.
# Example:
arr = np.fft.fftshift(np.array([0, 1, 2, 3]))
print(arr)


[2 3 0 1]


In [ ]:
# np.fft.ifftshift()
# Description: Shifts the zero-frequency component back to the beginning of the spectrum.
# Example:
arr = np.fft.ifftshift(np.array([0, 1, 2, 3]))
print(arr)


[2 3 0 1]


In [ ]:
# np.fft.fftfreq()
# Description: Returns the Discrete Fourier Transform sample frequencies.
# Example:
freqs = np.fft.fftfreq(8, d=0.1)
print(freqs)


[ 0.    1.25  2.5   3.75 -5.   -3.75 -2.5  -1.25]


In [ ]:
# np.fft.rfft()
# Description: Computes the one-dimensional discrete Fourier Transform for real input.
# Example:
arr = np.fft.rfft(np.array([1, 2, 3, 4]))
print(arr)


[10.+0.j -2.+2.j -2.+0.j]


In [ ]:
# np.fft.irfft()
# Description: Computes the inverse of the one-dimensional discrete Fourier Transform for real input.
# Example:
arr = np.fft.irfft(np.array([1, 2, 3, 4]))
print(arr)


[ 2.5        -0.66666667  0.         -0.16666667  0.         -0.66666667]


In [ ]:
# np.convolve()
# Description: Returns the discrete, linear convolution of two one-dimensional sequences.
# Example:
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])
convolution = np.convolve(a, b)
print(convolution)


[0.  1.  2.5 4.  1.5]


In [ ]:
# np.correlate()
# Description: Cross-correlates two one-dimensional sequences.
# Example:
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])
correlation = np.correlate(a, b, "full")
print(correlation)


[0.5 2.  3.5 3.  0. ]


In [ ]:
# np.cov()
# Description: Estimates a covariance matrix, given data and weights.
# Example:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
cov_matrix = np.cov(x, y)
print(cov_matrix)


[[ 1. -1.]
 [-1.  1.]]


In [ ]:
# np.corrcoef()
# Description: Returns Pearson product-moment correlation coefficients.
# Example:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
corr_coef = np.corrcoef(x, y)
print(corr_coef)


[[ 1. -1.]
 [-1.  1.]]


In [ ]:
# np.angle()
# Description: Returns the angle of the complex argument.
# Example:
z = np.array([1+1j, 1-1j])
angles = np.angle(z)
print(angles)


[ 0.78539816 -0.78539816]


In [ ]:
# np.real()
# Description: Returns the real part of the complex argument.
# Example:
z = np.array([1+1j, 1-1j])
real_part = np.real(z)
print(real_part)


[1. 1.]


In [ ]:
# np.imag()
# Description: Returns the imaginary part of the complex argument.
# Example:
z = np.array([1+1j, 1-1j])
imaginary_part = np.imag(z)
print(imaginary_part)


[ 1. -1.]


In [ ]:
# np.sinh()
# Description: Calculates the hyperbolic sine element-wise.
# Example:
arr = np.sinh(np.array([0, np.pi/2, np.pi]))
print(arr)


[ 0.          2.3012989  11.54873936]


In [ ]:
# np.cosh()
# Description: Calculates the hyperbolic cosine element-wise.
# Example:
arr = np.cosh(np.array([0, np.pi/2, np.pi]))
print(arr)


[ 1.          2.50917848 11.59195328]
