In [ ]:
pip install numpy

In [ ]:
import numpy as np
# np.array()
# Description: Creates an array.
# Example:
arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [ ]:
  # np.zeros()
# Description: Creates an array filled with zeros.
# Example:
arr = np.zeros(2,dtype = int )
print(arr)


[0 0]


In [ ]:
# np.ones()
# Description: Creates an array filled with ones.
# Example:
arr = np.ones(2 )
print(arr)


[1. 1.]


In [ ]:
# np.empty()
# Description: Creates an uninitialized array.
# Example:
import numpy as np
np.empty([1, 1])
arr = np.empty((3))
print(arr)


[1. 1. 1.]


In [ ]:
 # np.arange()
# Description: Creates an array with a range of values.
# Example:
arr = np.arange(0, 10)
print(arr)


[0 3 6 9]


In [ ]:
import numpy as np
# np.linspace()
# Description: Creates an array with evenly spaced values.
# Example:
arr = np.linspace(2, 10, 10)
print(arr)


[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


In [ ]:
# np.eye()
# Description: Creates an identity matrix.
# Example:
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# np.random.rand()
# Description: Generates an array with random values between 0 and 1.
# Example:
arr = np.random.rand(3, 3)
print(arr)


[[0.03774556 0.52912706 0.82145114]
 [0.23281794 0.9773571  0.13164252]
 [0.89592382 0.57079731 0.92861527]]


In [ ]:
# np.random.randn()
# Description: Generates an array with random values from a normal distribution.
# Example:
arr = np.random.randn(3, 3)
print(arr)


[[ 0.28221832 -0.83786529  0.72865629]
 [ 0.33771636  1.91729478  1.4167984 ]
 [-0.15842943 -3.20345319 -0.52554922]]


In [ ]:
# np.random.randint()
# Description: Generates random integers within a specified range.
# Example:
arr = np.random.randint(0, 100, (3, 3))
print(arr)


[[32 34 69]
 [28 10 95]
 [49 88 29]]


In [ ]:
# np.reshape()
# Description: Reshapes an array.
# Example:
arr = np.array([1, 2, 3, 4]).reshape(2, 2)
print(arr)


[[1 2]
 [3 4]]


In [ ]:
# np.transpose()
# Description: Transposes an array.
# Example:
arr = np.array([[1, 2], [3, 4]]).transpose()
print(arr)


[[1 3]
 [2 4]]


In [ ]:
# np.concatenate()
# Description: Concatenates two arrays.
# Example:
arr = np.concatenate(([1, 2], [3, 4]))
print(arr)


[1 2 3 4]


In [ ]:
# np.vstack()
# Description: Stacks arrays vertically.

# Example:
import numpy as np
a = np.array([(1,2,3,4),(3,4,5,5),(1,2,3,5)])
b = np.array([(1,2,3,4),(3,4,5,5),(1,2,3,6)])


# arr = np.vstack(([1, 2], [3, 4]))
# print(arr)

print(a)
print("Shape of array a is ", np.shape(a))
print(b)
print ("Shape of array b is ",np.shape(b))
print(np.vstack((a,b)))
print("Shape of arry after vstack is ", np.vstack((a,b)).shape)



[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 5]]
Shape of array a is  (3, 4)
[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 6]]
Shape of array b is  (3, 4)
[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 5]
 [1 2 3 4]
 [3 4 5 5]
 [1 2 3 6]]
Shape of arry after vstack is  (6, 4)


In [ ]:


# np.hstack()
# Description: Stacks arrays horizontally.
# Example:
# arr = np.hstack(([1, 2], [3, 4]))
# print(arr)


print(a)
print(b)
print (np.shape(a))
print (np.shape(b)) #jfhgjfhg
print(np.hstack((a,b)).shape)
print(np.hstack((a,b)))

[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 5]]
[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 6]]
(3, 4)
(3, 4)
(3, 8)
[[1 2 3 4 1 2 3 4]
 [3 4 5 5 3 4 5 5]
 [1 2 3 5 1 2 3 6]]


In [ ]:
import numpy as np

# Original array
data = np.array([1, 2, 3, 4, 5])  # Example with 5 elements

# Desired shape (e.g., 2x3, which requires 6 elements)
target_shape = (4, 4)

# Use np.resize to fit the target shape
reshaped_array = np.resize(data, target_shape)

print("Reshaped Array:")
print(reshaped_array)


Reshaped Array:
[[1 2 3 4]
 [5 1 2 3]
 [4 5 1 2]
 [3 4 5 1]]


In [ ]:
# np.split()
# Description: Splits an array into multiple sub-arrays.
# Example:
arr = np.split(np.array([1, 2, 3, 4]), 2)
print(arr)


[array([1, 2]), array([3, 4])]


In [ ]:
# np.hsplit()
# Description: Splits an array into multiple sub-arrays horizontally.
# Example:
arr = np.hsplit(np.array([[1, 2], [3, 4]]), 2)
print(arr)


[array([[1],
       [3]]), array([[2],
       [4]])]


In [ ]:
print(np.array([[1, 2], [3, 4]]))

[[1 2]
 [3 4]]


In [ ]:
# np.vsplit()
# Description: Splits an array into multiple sub-arrays vertically.
# Example:
arr = np.vsplit(np.array([[1, 2], [3, 4]]), 2)
print(arr)



[array([[1, 2]]), array([[3, 4]])]


In [ ]:
# np.sort()
# Description: Sorts an array.
# Example:
arr = np.sort(np.array([3, 1, 2]))
print(arr)


[1 2 3]


In [ ]:
# np.argsort()
# Description: Returns the indices that would sort an array.
# Example:
arr = np.argsort(np.array([3, 1, 2]))
#                          0  1  2
print(arr)


[1 2 0]


In [ ]:
# np.argmax()
# Description: Returns the index of the maximum value.
# Example:
arr = np.argmax(np.array([1, 2, 3]))
print(arr)


2


In [ ]:
# np.argmin()
# Description: Returns the index of the minimum value.
# Example:
arr = np.argmin(np.array([1, 2, 3]))
print(arr)


0


In [ ]:
# np.mean()
# Description: Calculates the mean of an array.
# Example:
arr = np.mean(np.array([1, 2, 3]))
print(arr)


2.0


In [ ]:
# np.median()
# Description: Calculates the median of an array.
# Example:
arr = np.median(np.array([1, 2, 3]))
print(arr)


2.0


In [ ]:
# np.std()
# Description: Calculates the standard deviation of an array.
# Example:
arr = np.std(np.array([1, 2, 3]))
print(arr)


0.816496580927726


In [ ]:
# prompt: can you explain me why is the result of "np.std(np.array([1, 2, 3]))" is 0.816496580927726

import numpy as np

# Calculate the standard deviation of the array [1, 2, 3]
std_dev = np.std(np.array([1, 2, 3]))
print(std_dev)

# Calculate the mean of the array
mean = np.mean(np.array([1, 2, 3]))
print(mean)

# Calculate the sum of squared differences from the mean
sum_sq_diff = np.sum((np.array([1, 2, 3]) - mean)**2)
print(sum_sq_diff)

# Calculate the variance
variance = sum_sq_diff / len(np.array([1, 2, 3]))
print(variance)

# Calculate the standard deviation
std_dev_manual = np.sqrt(variance)
print(std_dev_manual)


0.816496580927726
2.0
2.0
0.6666666666666666
0.816496580927726


In [ ]:
help(np.std)

Help on _ArrayFunctionDispatcher in module numpy:

std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
    Compute the standard deviation along the specified axis.
    
    Returns the standard deviation, a measure of the spread of a distribution,
    of the array elements. The standard deviation is computed for the
    flattened array by default, otherwise over the specified axis.
    
    Parameters
    ----------
    a : array_like
        Calculate the standard deviation of these values.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the standard deviation is computed. The
        default is to compute the standard deviation of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a standard deviation is performed over
        multiple axes, instead of a single axis or all the axes as before.
    dtype : dtype, optional
        Type to use in computing the standard